version: 0.0
os: linux

files:
# Path **inside** your repo/zip # Absolute path **on** the instance
- source: index.html
destination: /var/www/html/

hooks:
ApplicationStop:
- location: scripts/stop_server.sh
timeout: 300
runas: root

BeforeInstall:
- location: scripts/install_dependencies.sh
timeout: 300
runas: root

ApplicationStart:
- location: scripts/start_server.sh
timeout: 300
runas: root
